### PR TITLE
 Some fix for the permalink 

### LINKED ISSUE #3352: Wrong permalink
Open http://localhost:3000/contribs/gmf/apps/desktop_alt/?tree_groups=Edit%2CSnapping%2CSnapping%20tollerance%2CSnapping%20no%20edge%2CSnapping%20no%20vertex

the URL tis transformed as http://localhost:3000/contribs/gmf/apps/desktop_alt/?lang=fr&baselayer_ref=OSM%20map%20WMS&tree_groups=Edit%2CSnapping%2CSnapping%20tollerance%2CSnapping%20no%20edge%2CSnapping%20no%20vertex&tree_group_layers_Edit=line%2Cpolygon%2Cpoint&tree_group_layers_Snapping&tree_group_layers_Snapping%20tollerance&tree_group_layers_Snapping%20no%20edge&tree_group_layers_Snapping%20no%20vertex

What's that?
```
tree_group_layers_Snapping
tree_group_layers_Snapping%20tollerance
tree_group_layers_Snapping%20no%20edge
tree_group_layers_Snapping%20no%20vertex
```

When I work for a ling time (with reload) it's growing a lot ...

With the Group Cadastre I get:
```
tree_enable_ch.swisstopo.dreiecksvermaschung
tree_enable_ch.swisstopo.geologie-gravimetrischer_atlas
tree_enable_ch.swisstopo.geologie-geotechnik-gk500-lithologie_hauptgruppen
tree_enable_ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung
tree_enable_ch.are.alpenkonvention
tree_enable_ch.astra.ausnahmetransportrouten
```
Shouldn't be:

```
tree_enable_ch.swisstopo.dreiecksvermaschung=false
tree_enable_ch.swisstopo.geologie-gravimetrischer_atlas=false
tree_enable_ch.swisstopo.geologie-geotechnik-gk500-lithologie_hauptgruppen=false
tree_enable_ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung=false
tree_enable_ch.are.alpenkonvention=false
tree_enable_ch.astra.ausnahmetransportrouten=false
```

### PR DESCRIPTION
**Pull request by sbrunner**
fix  #3352

### CODE REVIEW

File: contribs/gmf/src/services/permalink.js [hunk 1]
```diff
@@ -1169,4 +1169,62 @@ gmf.Permalink.prototype.createFilterGroup_ = function(prefix, paramKeys) {
...
+gmf.Permalink.prototype.containsLayerName = function(layer, name) {
+  if (layer instanceof ol.layer.Group) {
+    for (const l of layer.getLayers().getArray()) {
+      if (this.containsLayerName(l, name)) {
+        return true;
+      }
+    }
+    return false;
+  } else {
+    return layer.get('layerNodeName') == name;
```
Comment (ger-benjamin) [inline contribs/gmf/src/services/permalink.js]: It's working with WMTS layers, WMS mixed layers, etc ? (all cases ?)

Comment (sbrunner) [reply contribs/gmf/src/services/permalink.js]: Just tested again, and effectively it's working for WMS and WMTS :-)
