### PR TITLE
Don't use boundlessgeo demo server anymore

### LINKED ISSUE #2113: Remove dependency on http://demo.opengeo.org/geoserver/wms
The Travis tests will too many times failed on error about that...

### PR DESCRIPTION
**Pull request by sbrunner**
fix #2113

### CODE REVIEW

**Comment by sbrunner** [comment]
+1, updated :-)

File: examples/backgroundlayer.js [hunk 1]
```diff
@@ -108,14 +108,19 @@ app.BackgroundlayerController.prototype.change = function() {
...
 app.BackgroundlayerController.prototype.getLayer_ = function(layerName) {
-  let source;
-  if (layerName === 'osm') {
-    source = new ol.source.OSM();
-  } else if (layerName === 'stamen') {
-    source = new ol.source.Stamen({
-      layer: 'watercolor'
-    });
-  }
+  const source = new ol.source.WMTS({
```
Comment (fredj) [inline examples/backgroundlayer.js]: Use `ngeo.source.AsitVD` ?

Comment (sbrunner) [inline examples/backgroundlayer.js]: Effectively, thanks :-)
