### PR TITLE
fix select/unselect node when layers have the same prefix

### LINKED ISSUE #1424: Unable to select/unselect all nodes in a group if one of its children node oparates for a WMTS layer
1. Go to https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop/
2. Clear your localStorage and reload
3. Click on OSM Function group to unselect all nodes 

- All nodes are unselected except the last one (named "ch.astra.ausnahmetransportrouten"). This node has a WMTS layer configuration attached. The other nodes have a WMS configuration.

4. Click again on OSM Function

- None of the nodes are unselected 

5. Click on the last node of OSM Function to have all child selected

- All nodes except the last one are unselected

### PR DESCRIPTION
**Pull request by olivierSemet**
FIX #1424

demo:

https://oliviersemet.github.io/ngeo/fix-regex-layersnames-same-prefix/examples/contribs/gmf/apps/desktop/?baselayer_ref=map&lang=fr&map_x=612600&map_y=148750&map_zoom=2&tree_group_layers_OSM%20functions=osm_time%2Cosm_time2%2Cosm_scale%2Cosm_open%2Cbank%2Crestaurant%2Ccafe%2Chalf_query%2Csrtm%2Caster&tree_groups=OSM%20functions

### CODE REVIEW

File: contribs/gmf/src/directives/layertree.js [hunk 1]
```diff
@@ -609,6 +610,21 @@ gmf.LayertreeController.prototype.toggleActive = function(treeCtrl) {
...
+ * @param  {string} allLayersNames all layers names currently enable for the
+ * WM(T)S layer
+ * @param  {string} subLayersNames layers names to search on allLayersNames
+ * @return {boolean} true if subLayersNames is in allLayersNames
+ * @private
+ */
+gmf.LayertreeController.prototype.searchLayersNames_ = function(allLayersNames,
+  subLayersNames) {
+  var pattern = new RegExp(subLayersNames + '(?=\,|$)');
+  return allLayersNames.search(pattern) >= 0;
```
Comment (sbrunner) [inline contribs/gmf/src/directives/layertree.js]: Will not work if we have for example two layers names `a.b`, `a_b`...
Why not doing `allLayersNames.split(',').indexOf(subLayersNames) >= 0;`?

**Comment by sbrunner** [comment]
Look good to me, I will merge it when Travis tests pass :-)

**Comment by olivierSemet** [comment]
@sbrunner could we merge?

**Comment by sbrunner** [comment]
Done :-)
