### PR TITLE
Store the name of the selected theme in localStorage

### LINKED ISSUE #1026: Theme not stored in local storage
The state of the tree is stored in local storage but the currently selected theme is not.
This may result in UI showing groups from a theme and the theme selector telling user that a different theme is chosen.

Procedure to reproduce:
 - load application,
 - select other theme than the default one (example Water Management),
 - groups from theme Water Management are correctly shown in tree,
 - reload page.

What happens:
 - groups from theme Water Management are shown in layer tree,
 - theme OSM is selected in theme selector.

Expected:
In **flush mode**, the theme which was selected before reload should be selected again.

Supersedes #1012.

https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop/index.html I get:
issue

### PR DESCRIPTION
**Pull request by olivierSemet**
Close #1026 

**Flush you localStorage before test**

Demo: https://oliviersemet.github.io/ngeo/store-theme-in-localstorage/examples/contribs/gmf/apps/desktop/

1. Load the [app](https://oliviersemet.github.io/ngeo/store-theme-in-localstorage/examples/contribs/gmf/apps/desktop/) with the default theme
2. Select any theme but not the default one (OSM)
3. Open the [app](https://oliviersemet.github.io/ngeo/store-theme-in-localstorage/examples/contribs/gmf/apps/desktop/) into an other tab

- [x] The name of the theme displayed matches the previous selected theme 
- [x] Url contains the good theme

@fredj @pgiraud @sbrunner

### CODE REVIEW

File: src/services/statemanager.js [hunk 1]
```diff
@@ -110,13 +129,24 @@ ngeo.StateManager.prototype.getInitialValue = function(key) {
  * @param {Object.<string, string>} object Object.
  */
 ngeo.StateManager.prototype.updateState = function(object) {
-  this.ngeoLocation.updateParams(object);
+  var locationObject = {};
+  Object.keys(/** @type {!Object} */(object)).forEach(copyWithoutExcludedKeys,
```
Comment (fredj) [inline src/services/statemanager.js]: Instead of casing the object to `{!Object}` the code could be changed with:
```diff
diff --git a/src/services/statemanager.js b/src/services/statemanager.js
index a77c733..95043d4 100644
--- a/src/services/statemanager.js
+++ b/src/services/statemanager.js
@@ -17,7 +17,7 @@ ngeo.StateManager = function(ngeoLocation) {
 
   /**
    * Object representing the application's initial state.
-   * @type {Object.<string ,string>}
+   * @type {!Object.<string ,string>}
    */
   this.initialState = {};
 
@@ -107,7 +107,7 @@ ngeo.StateManager.prototype.getInitialValue = function(key) {
 
 /**
  * Update the application state with the values in `object`.
- * @param {Object.<string, string>} object Object.
+ * @param {!Object.<string, string>} object Object.
  */
 ngeo.StateManager.prototype.updateState = function(object) {
   this.ngeoLocation.updateParams(object);
```

Comment (olivierSemet) [inline src/services/statemanager.js]: Yes thanks @fredj

**Comment by fredj** [comment]
LGTM, @sbrunner please merge if you're happy with this change

**Comment by olivierSemet** [comment]
IMO it could be great to show that someone tested the app by checking the check boxes.

**Comment by sbrunner** [comment]
Thanks :-)
