### PR TITLE
Fix decimal / precision mixage and unworking

### LINKED ISSUE #2664: gmf-mobile-measurelength-decimals is not used
the mobileMeasureLengthDirective api
http://camptocamp.github.io/ngeo/master/apidoc/gmf.mobileMeasureLengthDirective.html
say we can use a gmf-mobile-measurelength-decimals option.
but that option value is never used,
see:

https://github.com/camptocamp/ngeo/blob/master/src/ol-ext/interaction/measure.js#L275-L285

since the decimal, according to @sbrunner has no meaning (see with him directly), remove that unused gmf-mobile-measurelength-decimals option

### PR DESCRIPTION
**Pull request by sbrunner**
fix #2664

### CODE REVIEW

File: contribs/gmf/src/directives/mobilemeasurelength.js [hunk 1]
```diff
@@ -113,6 +112,12 @@ gmf.MobileMeasureLengthController = function($scope, ngeoDecorateInteraction, $f
    * @type {number|undefined}
    * @export
    */
+  this.precision;
+
+  /**
+   * @type {number|undefined}
+   * @export
+   */
   this.decimals;
```
Comment (fredj) [inline contribs/gmf/src/directives/mobilemeasurelength.js]: `decimals` is removed from the scope, is `this.decimals` still useful?

Comment (sbrunner) [inline contribs/gmf/src/directives/mobilemeasurelength.js]: Just removed :-)
