### PR TITLE
Escape sourceLabel ids when invalid characters are present

### LINKED ISSUE #3273: Display query grid: No titles in tabs of second row
Project:
* GitHub URL: https://github.com/camptocamp/baselstadt_mapbs
* GeoMapFish version: 2.2.1

Steps to reproduce the issue:
* do a query over a surface
* open a tab in the second row
* the titles of the tabs in the second row are broken

Result:
display_query_grid

As soon as there are two rows of tabs in the display query grid the titles are broken.

### PR DESCRIPTION
**Pull request by llienher**
Fixes #3273.

With this fix, we escape the IDs (generated from the value in ctrl.mergeTabs for merged tabs or OL datasource). If an invalid value would result in an invalid ID selector (css), then the value is stripped from unauthorized characters. Other change is the use of the datasource IDs for the HTML ids instead of the label value that contained spaces, etc.

Ideally ids defined in the ctrl.mergeTabs should have no spaces, or any specific characters such as parentheses, brackets, etc. This fix allow all project to work without changing ids manually, but if possible having a correct value is just best practice...

In that context I changed the value in our desktop example, while the fix was tested on the previous value, 'OSM time merged'.

### CODE REVIEW

**Comment by llienher** [comment]
@ger-benjamin I refactored the code. Now it is escaped at data generation (before the function that going to fill the grid). I did the change to use Ids again in the HTML instead of the labels. Labels are still used for the tab labels, so nothing change for the user.

File: contribs/gmf/src/directives/displayquerygrid.js [hunk 1]
```diff
@@ -381,6 +382,26 @@ gmf.DisplayquerygridController.prototype.hasOneWithTooManyResults_ = function()
   return this.ngeoQueryResult.sources.some(source => source.tooManyResults);
 };
 
+/**
+ * Returns an escaped value.
+ * @param {string|number} value A value to escape.
+ * @returns {string|number} value An escaped valjue.
```
Comment (ger-benjamin) [inline contribs/gmf/src/directives/displayquerygrid.js]: typo

**Comment by llienher** [comment]
@ger-benjamin I added two merged tabs in desktop_alt to make sure we have correct testing setup.
