### PR TITLE
Fix the Zoom to scale display and action!!!

### LINKED ISSUE #2265: 'Zoom to' button does not zoom enough
Version 2.1.1

To test : 
1°/ Go to https://preprod.cartoriviera.ch/v2/mobile/ 
2°/ Zoom out to see all communes
3°/ Go to theme "Infrastructures"
4°/ Click on the zoomto button of layer "Hydrantes (EP)" -> the application does not zoom enough, blue circles are not visible, you have to zoom manually to see them

### PR DESCRIPTION
**Pull request by sbrunner**
fix #2265

### CODE REVIEW

File: contribs/gmf/src/directives/layertree.js [hunk 1]
```diff
@@ -362,19 +362,17 @@ gmf.LayertreeController.prototype.listeners = function(scope, treeCtrl) {
  * Return 'out-of-resolution' if the current resolution of the map is out of
  * the min/max resolution in the node.
  * @param {gmfThemes.GmfLayerWMS} gmfLayerWMS the GeoMapFish Layer WMS.
- * @return {?string} 'out-of-resolution' or null.
+ * @return {string|undefined} 'out-of-resolution' or null.
```
Comment (fredj) [inline contribs/gmf/src/directives/layertree.js]: `{string|undefined}` but the function only returns a number or null ?

File: contribs/gmf/src/directives/layertree.js [hunk 2]
```diff
@@ -362,19 +362,17 @@ gmf.LayertreeController.prototype.listeners = function(scope, treeCtrl) {
...
   var resolution = this.map.getView().getResolution();
-  var maxExtent = gmfLayerWMS.maxResolutionHint;
-  var minExtent = gmfLayerWMS.minResolutionHint;
-  if (minExtent !== undefined && resolution < minExtent ||
-      maxExtent !== undefined && resolution > maxExtent) {
+  if (gmfLayerWMS.minResolutionHint !== undefined && resolution < gmfLayerWMS.minResolutionHint ||
+      gmfLayerWMS.maxResolutionHint !== undefined && resolution > gmfLayerWMS.maxResolutionHint) {
     style = 'out-of-resolution';
   }
-  return style || null;
```
Comment (fredj) [inline contribs/gmf/src/directives/layertree.js]: what if `style == 0` ? null will be returned

Comment (fredj) [inline contribs/gmf/src/directives/layertree.js]: I probably need more sleep ...
