### PR TITLE
Use the matrixSet value from the WMTS layer config

### LINKED ISSUE #3555: ngeo doesn't take into account "tilematrixset" of admin for WMTS layers
Version 2.2.2

When configuring a WMTS layer in admin interface and specifying the tilematrixset (for a layer with 2 tilematrixset available), this value is not taken into account in application, and the default tilematrixset is used. To reproduce : go to https://preprod.cartoriviera.ch/new/ -> the tiles of layer asitvd.fond_cadastral are loaded with tilematrixset 21781 :  

https://ows.asitvd.ch/wmts?layer=asitvd.fond_cadastral&style=default&tilematrixset=21781&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fpng&TileMatrix=19&TileCol=24&TileRow=38&DIM1=default&ELEVATION=0

But the tiles should have 2056 instead of 21781 : 

https://ows.asitvd.ch/wmts?layer=asitvd.fond_cadastral&style=default&tilematrixset=2056&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fpng&TileMatrix=19&TileCol=24&TileRow=38&DIM1=default&ELEVATION=0

So ngeo does a reprojection and the final quality is bad. The admin config is the followin : 
image

Here is the getcapabilities : https://ows.asitvd.ch/wmts?service=wmts&request=getcapabilities

### PR DESCRIPTION
**Pull request by fredj**
fixes #3555

### CODE REVIEW

File: src/services/layerHelper.js [hunk 1]
```diff
@@ -106,12 +106,13 @@ ngeo.LayerHelper.prototype.createBasicWMSLayer = function(sourceURL,
  * as key 'capabilitiesStyles' as param of the new layer.
  * @param {string} capabilitiesURL The getCapabilities url.
  * @param {string} layerName The name of the layer.
+ * @param {string|undefined} opt_matrixSet Optional WMTS matrix set.
```
Comment (sbrunner) [inline src/services/layerHelper.js]: I don't remember but the type shouldn't be `string=`?

Comment (fredj) [reply src/services/layerHelper.js]: yes, will change
