### PR TITLE
Some fix in the permalink

### LINKED ISSUE #2255: Permalink does not work on ngeo mobile
Version 2.1.1. To reproduce : 

1°/ Go to https://preprod.cartoriviera.ch/v2/mobile/
2°/ Change theme and zoom somewhere
3°/ Copy the URL
4°/ Paste it in a new browser or tab -> application loads on initial extent and default theme...

You can try with this URL too, that should go to theme cadastre and activate some layers : 
https://preprod.cartoriviera.ch/v2/mobile/theme/cadastre?lang=fr&tree_group_layers_default_mobile_group=tp_arret_bus%2Ctp_arret_train%2Ctp_ligne_bus%2Ctp_ligne_train&baselayer_ref=plan_cadastral_201701&map_x=553852&map_y=146418&map_zoom=7&tree_groups=cadastre%2Ccouverture_du_sol&tree_group_layers_cadastre=batiments_egid%2Climite_commune%2Cbatiments_projetes

### PR DESCRIPTION
**Pull request by sbrunner**
Fix  #2255

### CODE REVIEW

File: contribs/gmf/src/services/permalink.js [hunk 1]
```diff
@@ -513,12 +511,11 @@ gmf.Permalink.prototype.getMapCrosshair = function() {
 
 /**
  * Get the tooltip text from the state manager.
- * @return {?string} Tooltip text.
+ * @return {stringi|undefined} Tooltip text.
```
Comment (fredj) [inline contribs/gmf/src/services/permalink.js]: `string` instead of `stringi`

Comment (sbrunner) [inline contribs/gmf/src/services/permalink.js]: :-)
