### PR TITLE
Some docs fix

### LINKED ISSUE #3255: Inconsistency between code and documentation in displayquerygridComponent
In the documentation of the _displayquerygridComponent_ the html attribute for defining the style of the selected feature is called _gmf-displayquerygrid-selectedfeaturestyle_ (https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/displayquerygrid.js#L69 and https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/displayquerygrid.js#L75). But in the code the binding looks for the html attribute _gmfDisplayquerygrid**Source**selectedfeaturestyle_ (https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/displayquerygrid.js#L93).
Which one is the html attribute to use?

Project:

* GitHub URL: https://github.com/camptocamp/ngeo
* GeoMapFish version: 2.2

### PR DESCRIPTION
**Pull request by sbrunner**
Fix #3255

### CODE REVIEW

File: contribs/gmf/src/directives/displayquerygrid.js [hunk 1]
```diff
@@ -86,7 +86,7 @@ gmf.displayquerygridComponent = {
   bindings: {
     'active': '=?gmfDisplayquerygridActive',
     'featuresStyleFn': '&gmfDisplayquerygridFeaturesstyle',
-    'selectedFeatureStyleFn': '&gmfDisplayquerygridSourceselectedfeaturestyle',
+    'selectedFeatureStyleFn': '&gmfDisplayquerygridSelectedfeaturestyle',
```
Comment (ger-benjamin) [inline contribs/gmf/src/directives/displayquerygrid.js]: So, now the attribute name will be: 
`gmf-displayquerygrid-selectedfeaturestyle`
(it was `gmf-displayquerygrid-sourceselectedfeaturestyle`)

It is what you want ?

Comment (ger-benjamin) [reply contribs/gmf/src/directives/displayquerygrid.js]: According to the doc, yes.

Comment (ger-benjamin) [reply contribs/gmf/src/directives/displayquerygrid.js]: And I don't see any use of it...
