### PR TITLE
Fixing WMTS node not selected/unselected when clicking on a group

### LINKED ISSUE #1424: Unable to select/unselect all nodes in a group if one of its children node oparates for a WMTS layer
1. Go to https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop/
2. Clear your localStorage and reload
3. Click on OSM Function group to unselect all nodes 

- All nodes are unselected except the last one (named "ch.astra.ausnahmetransportrouten"). This node has a WMTS layer configuration attached. The other nodes have a WMS configuration.

4. Click again on OSM Function

- None of the nodes are unselected 

5. Click on the last node of OSM Function to have all child selected

- All nodes except the last one are unselected

### PR DESCRIPTION
**Pull request by olivierSemet**
FIX #1424 

Related PR on server side: https://github.com/camptocamp/c2cgeoportal/pull/2328

As soon as a node with type set to "WMTS" get a property layer for its layer name, I'll provide an example.

@sbrunner  can you review please?

### CODE REVIEW

File: contribs/gmf/src/directives/layertree.js [hunk 1]
```diff
@@ -578,6 +574,26 @@ gmf.LayertreeController.prototype.toggleActive = function(treeCtrl) {
...
+ */
+gmf.LayertreeController.prototype.getLayersNames_ = function(node) {
+  var type = gmf.Themes.getNodeType(node);
+  switch (type) {
+    case gmf.Themes.NodeType.WMS:
+      return node.layers;
+    case gmf.Themes.NodeType.WMTS:
+      return node.layer;
+    default:
+      throw new Error('node wrong type to get layer(s) name(s): ' + type);
```
Comment (ger-benjamin) [inline contribs/gmf/src/directives/layertree.js]: Please start your message with a capital N.

File: contribs/gmf/src/directives/layertree.js [hunk 2]
```diff
@@ -578,6 +574,26 @@ gmf.LayertreeController.prototype.toggleActive = function(treeCtrl) {
 
 
 /**
+ * LayertreeController.prototype.getLayersNames_ - Get the layer(s) name(s)
```
Comment (ger-benjamin) [inline contribs/gmf/src/directives/layertree.js]: Have you any reason to name function in this comment ? Or its an error ?

**Comment by ger-benjamin** [comment]
Seem alright. 

> As soon as a node with type set to "WMTS" get a property layer for its layer name, I'll provide an example.

It is ready ?

File: contribs/gmf/src/directives/layertree.js (hunk 2 above)
Comment (olivierSemet) [inline contribs/gmf/src/directives/layertree.js]: No, this is automatically generated by my IDE. Should I remove it?

File: contribs/gmf/src/directives/layertree.js (hunk 1 above)
Comment (olivierSemet) [inline contribs/gmf/src/directives/layertree.js]: Ok. should also be modified on https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/layertree.js#L295 and https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/layertree.js#L266

Comment (ger-benjamin) [inline contribs/gmf/src/directives/layertree.js]: That will be a nice to have yes.

File: contribs/gmf/src/directives/layertree.js (hunk 2 above)
Comment (ger-benjamin) [inline contribs/gmf/src/directives/layertree.js]: I think that's not useful. A redundant information.
So IMO, yes.

Comment (olivierSemet) [inline contribs/gmf/src/directives/layertree.js]: ok

**Comment by olivierSemet** [comment]
@sbrunner do you have some update about it?

**Comment by sbrunner** [comment]
Not actually :-/

**Comment by olivierSemet** [comment]
@sbrunner @ger-benjamin 
Thanks to your job on server side, it works well now, check it out :)
https://oliviersemet.github.io/ngeo/1424-select-unselect-all-child-nodes/examples/contribs/gmf/apps/desktop/

**Comment by sbrunner** [comment]
When I click on the `Functions OSM` the layer `Café` will not be disable ...

**Comment by sbrunner** [comment]
Also that's looks good :-)

**Comment by olivierSemet** [comment]
@sbrunner yes I saw it also. We should report the bug in an other issue since this is a different problem

**Comment by sbrunner** [comment]
Done #1504 :-)

**Comment by olivierSemet** [comment]
Thank you @sbrunner.

**Comment by olivierSemet** [comment]
@sbrunner can we merge?

**Comment by fredj** [comment]
LGTM
