### PR TITLE
Use absolutes URL for the partiales

### LINKED ISSUE #1171: layertree partial fails loading in desktop app
Path to the template isn't correct after the url change.
Seem to be related to this commit acefa391ce72b7c9f936b5a6e87d5d03643c4838

### PR DESCRIPTION
**Pull request by sbrunner**
fix  #1171 
replace  #1121

### CODE REVIEW

File: contribs/gmf/apps/desktop/default.js [hunk 1]
```diff
@@ -1,12 +1,27 @@
+var urlElements = window.location.pathname.split('/');
+urlElements.pop();
+urlElements.pop();
+urlElements.pop();
```
Comment (tsauerwein) [inline contribs/gmf/apps/desktop/default.js]: I looks like you are programming in [Logo](https://en.wikipedia.org/wiki/Logo_%28programming_language%29).. ;)

This could be:

    var gmfUrlElements = urlElements.slice(0, urlElements.length - 3);

Comment (sbrunner) [inline contribs/gmf/apps/desktop/default.js]: :-) +1

**Comment by sbrunner** [comment]
Thanks @tsauerwein, mutch better :-)

File: contribs/gmf/apps/desktop/default.js [hunk 2]
```diff
@@ -1,12 +1,21 @@
+var urlElements = window.location.pathname.split('/');
+
+gmfUrlElements = urlElements.slice(0, urlElements.length - 3);
```
Comment (tsauerwein) [inline contribs/gmf/apps/desktop/default.js]: `var gmfUrlElements = ...`

File: contribs/gmf/apps/desktop/default.js [hunk 3]
```diff
@@ -1,12 +1,21 @@
...
+gmfUrlElements.push('src', 'directives', 'partials')
```
Comment (tsauerwein) [inline contribs/gmf/apps/desktop/default.js]: missing semicolon

File: contribs/gmf/apps/desktop/default.js [hunk 4]
```diff
@@ -1,12 +1,21 @@
...
+
+ngeoUrlElements = urlElements.slice(0, urlElements.length - 5);
```
Comment (tsauerwein) [inline contribs/gmf/apps/desktop/default.js]: same here

File: contribs/gmf/apps/desktop/default.js [hunk 5]
```diff
@@ -1,12 +1,21 @@
+var urlElements = window.location.pathname.split('/');
+
+var gmfUrlElements = urlElements.slice(0, urlElements.length - 3);
+gmfUrlElements.push('src', 'directives', 'partials')
```
Comment (tsauerwein) [inline contribs/gmf/apps/desktop/default.js]: missing semicolons

Comment (fredj) [inline contribs/gmf/apps/desktop/default.js]: This is strange than eslint didn't detect it: #1072

Comment (tsauerwein) [inline contribs/gmf/apps/desktop/default.js]: Are these files not scanned by eslint? The missing `var ...` was also not detected.

Comment (sbrunner) [inline contribs/gmf/apps/desktop/default.js]: Fixed with https://github.com/camptocamp/ngeo/commit/3cde1d780f8a72451231a82b334804fb43dbf472
